#!/bin/sh
set -e

cat >index.html <<HTML
<!doctype html>
<html lang=en-US>
<!--
Nerds:

You can link to any particular fraction with #{x}/{y} or any whole millimeter with #{X}mm.
The corresponding row will be displayed with a highlighter-yellow background.

The scripts for generating this site are at <https://github.com/kemitchell/inch.kemitchell.com>.
-->
  <head>
    <meta charset=UTF-8>
    <meta name=viewport content="width=device-width, initial-scale=1">
    <title>Fractional Inch</title>
    <link rel=stylesheet href=styles.css>
  </head>
  <body>
  <main>
$(./output_table)
  </main>
  </body>
</html>
HTML

tidy \
  --custom-tags blocklevel \
  --doctype omit \
  --indent-spaces 2 \
  --tidy-mark no \
  -indent \
  -modify \
  -wrap 0 \
  -quiet \
  ./index.html
