#!/bin/sh
set -e

cat >index.html <<HTML
<!doctype html>
<html lang=en-US>
  <head>
    <meta charset=UTF-8>
    <meta name=viewport content="width=device-width, initial-scale=1">
    <title>Volume</title>
    <link rel=stylesheet href=styles.css>
  </head>
  <body>
  <main>
$(./output_table)
  </main>
  </body>
</html>
HTML

tidy \
  --custom-tags blocklevel \
  --indent-spaces 2 \
  --tidy-mark no \
  -indent \
  -modify \
  -wrap 0 \
  -quiet \
  ./index.html
