#!/bin/sh
set -e
cat >index.html <<HTML
<!doctype html>
<html lang=en-US>
  <head>
    <meta charset=UTF-8>
    <meta name=viewport content="width=device-width, initial-scale=1">
    <title>Fractional Inch</title>
    <link rel=stylesheet href=https://css.kemitchell.com/readable.css>
    <style>
table {
  border-spacing: 0;
  tbody {
    td {
      vertical-align: middle;
      padding: 0.rem;
    }
    tr:nth-child(even) {
      background: #eee;
    }
  }
}
    </style>
  </head>
  <body>
  <main>
$(npx kemarkdown < table.md)
  </main>
  </body>
</html>
HTML
