#!/bin/sh
set -e
cat >index.html <<HTML
<!doctype html>
<html lang=en-US>
  <head>
    <meta charset=UTF-8>
    <meta name=viewport content="width=device-width, initial-scale=1">
    <title>Fractional Inch</title>
    <style>
table {
  margin: 0 auto;
  border-spacing: 0;
  td, th {
    padding: 0.5rem;
  }
  thead {
    th {
      text-align: left;
      vertical-align: bottom;
    }
    tr:last-child {
      td, th {
        border-bottom: 1px solid black;
      }
    }
  }
  tbody {
    td {
      vertical-align: middle;
      padding: 0.5rem;
    }
    @media print {
      tr {
        border-bottom: 1px solid #777;
      }
    }
    @media screen {
      tr:nth-child(even) {
        background: #eee;
      }
    }
  }
}
    </style>
  </head>
  <body>
  <main>
$(npx kemarkdown < table.md)
  </main>
  </body>
</html>
HTML
