#!/usr/bin/env ruby
# frozen_string_literal: true

records = []

def ounces_to_ml(ounces)
  ounces * 29.5735295625
end

def ml_to_ounces(ml)
  ml / 29.5735295625
end

ml = [100, 250, 500, 750, 1000]
ounces = [8, 16, 24]

ml.each do |ml|
  records << { ml: ml, ounces: ml_to_ounces(ml) }
end

ounces.each do |ounces|
  records << { ml: ounces_to_ml(ounces), ounces: ounces }
end

records << { pints: 1, ounces: 16, ml: ounces_to_ml(16) }
records << { quarts: 1, pints: 2, ounces: 32, ml: ounces_to_ml(32) }

rows = records
       .group_by { |x| x[:ml] }
       .map do |_, matching|
         row = {}
         matching.each do |record|
           record.each do |key, value|
             row[key] = value
           end
         end
         row
       end
       .sort_by { |row| row[:ml] }

puts '<table>'

puts '<thead>'
puts '<tr>'
puts '<th>Milliliters</th>'
puts '<th>Ounces</th>'
puts '<th>Pints</th>'
puts '<th>Quarts</th>'
puts '</tr>'
puts '</thead>'

puts '<tbody>'
rows.each do |row|
  puts '<tr>'
  puts "<td>#{row[:ml]}</td>"
  puts "<td>#{row[:ounces]}</td>"
  puts "<td>#{row[:pints]}</td>"
  puts "<td>#{row[:quarts]}</td>"
  puts '</tr>'
end
puts '</tbody>'

puts '</table>'
